#' Deploy a Document
#'
#' Deploys an application consisting of a single R Markdown document or other
#' single file (such as an HTML or PDF document).
#'
#' @param doc Path to the document to deploy.
#' @param ... Additional arguments to [deployApp()]. Do not supply `appDir`,
#'   `appFiles`, or `appPrimaryDoc`; these three parameters are automatically
#'   generated by `deployDoc` from the document.
#'
#' @details When deploying an R Markdown document, any files which are required
#'   to render and display the file must be deployed.
#'
#'   This method discovers these additional files using
#'   [rmarkdown::find_external_resources()] from \pkg{rmarkdown}.
#'
#'   If you find that the document is missing dependencies, either specify the
#'   dependencies explicitly in the document (the documentation for
#'   [rmarkdown::find_external_resources()] explains how to do this), or call
#'   [deployApp()] directly and specify your own file list in the `appFiles`
#'   parameter.
#'
#' @family Deployment functions
#' @export
deployDoc <- function(doc, ...) {
  doc <- standardizeSingleDocDeployment(doc)
  deployApp(
    appDir = doc$appDir,
    appPrimaryDoc = doc$appPrimaryDoc,
    appFiles = doc$appFiles,
    ...
  )
}

standardizeSingleDocDeployment <- function(path,
                                           quiet = FALSE,
                                           error_call = caller_env(),
                                           error_arg = caller_arg(path)) {
  check_installed(
    "rmarkdown",
    version = "0.5.2",
    reason = "to deploy individual R Markdown documents"
  )
  check_file(path, error_call = error_call, error_arg = error_arg)
  path <- normalizePath(path)

  withStatus <- withStatus(quiet)

  if (isShinyRmd(path)) {
    # deploy entire directory
    appFiles <- NULL
  } else if (isStaticFile(path)) {
    # deploy file + dependenciy
    withStatus("Discovering document dependencies", {
      resources <- rmarkdown::find_external_resources(path)
    })
    appFiles <- c(basename(path), resources$path)
  } else {
    # deploy just the file
    appFiles <- basename(path)
  }

  list(
    appDir = dirname(path),
    appPrimaryDoc = basename(path),
    appFiles = appFiles
  )
}

isStaticFile <- function(path) {
  ext <- tolower(tools::file_ext(path))
  ext %in% c("rmd", "qmd", "html", "htm")
}
